version: '3.8'
services:

    db:
        image: postgres:14.1-alpine
        restart: always
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
            # copy the sql script to create tables
            - ./sql/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
        environment:
            - POSTGRES_DB=dana
            - POSTGRES_USER=dana
            - POSTGRES_PASSWORD=dana123
        ports:
        - '5434:5432'

    engine:
        build: .
        container_name: engine
        depends_on:
            - db
        volumes:
            - ./data_sources:/usr/local/dana_tech_test/data_sources
        stdin_open: true
        tty: true


volumes:
  db:
    driver: local
