INSERT INTO ods.user (
    user_id,
    name,
    review_count,
    yelping_since,
    useful,
    funny,
    cool,
    elite,
    friends,
    fans,
    average_stars,
    compliment_hot,
    compliment_more,
    compliment_profile,
    compliment_cute,
    compliment_list,
    compliment_note,
    compliment_plain,
    compliment_cool,
    compliment_funny,
    compliment_writer,
    compliment_photos
)
SELECT
    user_id                          AS user_id,
    name                             AS name,
    cast(review_count AS int)        AS review_count,
    cast(yelping_since AS timestamp) AS yelping_since,
    useful                           AS useful,
    funny                            AS funny,
    cool                             AS cool,
    elite                            AS elite,
    friends                          AS friends,
    fans                             AS fans,
    average_stars                    AS average_stars,
    compliment_hot                   AS compliment_hot,
    compliment_more                  AS compliment_more,
    compliment_profile               AS compliment_profile,
    compliment_cute                  AS compliment_cute,
    compliment_list                  AS compliment_list,
    compliment_note                  AS compliment_note,
    compliment_plain                 AS compliment_plain,
    compliment_cool                  AS compliment_cool,
    compliment_funny                 AS compliment_funny,
    compliment_writer                AS compliment_writer,
    compliment_photos                AS compliment_photos
FROM staging.user;